// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.WuZiQi
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:9f400f20-f80b-4bd1-99f7-e0fd00f4a991
    public partial class UIHomePanel
    {
        
        public const string NAME = "UIHomePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button Button;
        
        private UIHomePanelData mPrivateData = null;
        
        public UIHomePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIHomePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Button = null;
            mData = null;
        }
    }
}
