// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Prefabs
    {
        public const string BundleName = "prefabs";
        public const string BLACKCHESS = "blackchess";
        public const string GAMEPLAYROOT = "gameplayroot";
        public const string WHITECHESS = "whitechess";
    }
    public class Uigameover_prefab
    {
        public const string BundleName = "uigameover_prefab";
        public const string UIGAMEOVER = "uigameover";
    }
    public class Uisprites
    {
        public const string BundleName = "uisprites";
        public const string BLACKWIN = "blackwin";
        public const string WHITEWIN = "whitewin";
    }
}
